apiVersion: v1
stringData:
  password: $GITLAB_TOKEN # Token here!
  project: default
  type: git
  url: https://somegitrepo.com/infra/argocd.git # Repo url
  username: git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: git-repository
  namespace: argocd
type: Opaque

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: testapp
    repoURL: https://github.com/koorikla/local-argocd.git # Repo url to the helmchart, reccomended to put to your own so you can try commiting
    targetRevision: HEAD # Branch
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true


---
## Starting from here are advanced operators and CRD's

# Strimzy kafka cluster operator that manages kafka clusters inside of k8s

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzy-kafka-operator
  namespace: argocd
spec:
  destination:
    namespace: strimzy-kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helm-charts/helm3/strimzi-kafka-operator/
    repoURL: https://github.com/strimzi/strimzi-kafka-operator.git 
    targetRevision: 0.28.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

---

# ArgoCD can manage ArgoCD itself

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: charts/argo-cd/
    repoURL: https://github.com/argoproj/argo-helm.git 
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

---

# Custom helmchart that Deploys CRD-s (Strimzy kafka cluster, topic and user)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster-and-topic-example
  namespace: argocd
spec:
  destination:
    namespace: strimzy-kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: kafka-cluster-and-topic
    repoURL: https://github.com/koorikla/local-argocd.git 
    targetRevision: HEAD # Branch
  syncPolicy:
    syncOptions:
    - CreateNamespace=true